-- Generated by Prisma migrate diff. Quiesce all old API and orchestrator writers before applying.
-- Retain ownership reservations on rollback; restoring the old unique index needs a collision audit.
-- DropIndex
DROP INDEX "Integration_organizationId_internalId_key";

-- CreateTable
CREATE TABLE "BizzbloxSocialAccountOwnership" (
    "providerIdentifier" TEXT NOT NULL,
    "externalAccountId" TEXT NOT NULL,
    "organizationId" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "BizzbloxSocialAccountOwnership_pkey" PRIMARY KEY ("providerIdentifier","externalAccountId")
);

-- CreateIndex
CREATE INDEX "BizzbloxSocialAccountOwnership_organizationId_idx" ON "BizzbloxSocialAccountOwnership"("organizationId");

-- CreateIndex
CREATE UNIQUE INDEX "Integration_organizationId_providerIdentifier_internalId_key" ON "Integration"("organizationId", "providerIdentifier", "internalId");

-- AddForeignKey
ALTER TABLE "BizzbloxSocialAccountOwnership" ADD CONSTRAINT "BizzbloxSocialAccountOwnership_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "Organization"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

